// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteFail2banIPReader is a Reader for the DeleteFail2banIP structure.
type DeleteFail2banIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFail2banIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFail2banIPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteFail2banIPNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewDeleteFail2banIPMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteFail2banIPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteFail2banIPOK creates a DeleteFail2banIPOK with default headers values
func NewDeleteFail2banIPOK() *DeleteFail2banIPOK {
	return &DeleteFail2banIPOK{}
}

/* DeleteFail2banIPOK describes a response with status code 200, with default header values.

Successful operation
*/
type DeleteFail2banIPOK struct {
}

func (o *DeleteFail2banIPOK) Error() string {
	return fmt.Sprintf("[DELETE /fail2ban/{ip}][%d] deleteFail2banIpOK ", 200)
}

func (o *DeleteFail2banIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFail2banIPNotFound creates a DeleteFail2banIPNotFound with default headers values
func NewDeleteFail2banIPNotFound() *DeleteFail2banIPNotFound {
	return &DeleteFail2banIPNotFound{}
}

/* DeleteFail2banIPNotFound describes a response with status code 404, with default header values.

IP was not found
*/
type DeleteFail2banIPNotFound struct {
}

func (o *DeleteFail2banIPNotFound) Error() string {
	return fmt.Sprintf("[DELETE /fail2ban/{ip}][%d] deleteFail2banIpNotFound ", 404)
}

func (o *DeleteFail2banIPNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFail2banIPMethodNotAllowed creates a DeleteFail2banIPMethodNotAllowed with default headers values
func NewDeleteFail2banIPMethodNotAllowed() *DeleteFail2banIPMethodNotAllowed {
	return &DeleteFail2banIPMethodNotAllowed{}
}

/* DeleteFail2banIPMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type DeleteFail2banIPMethodNotAllowed struct {
}

func (o *DeleteFail2banIPMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /fail2ban/{ip}][%d] deleteFail2banIpMethodNotAllowed ", 405)
}

func (o *DeleteFail2banIPMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFail2banIPInternalServerError creates a DeleteFail2banIPInternalServerError with default headers values
func NewDeleteFail2banIPInternalServerError() *DeleteFail2banIPInternalServerError {
	return &DeleteFail2banIPInternalServerError{}
}

/* DeleteFail2banIPInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type DeleteFail2banIPInternalServerError struct {
}

func (o *DeleteFail2banIPInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /fail2ban/{ip}][%d] deleteFail2banIpInternalServerError ", 500)
}

func (o *DeleteFail2banIPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
