// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pjotrscholtze/dmailserver-rest-api/models"
)

// GetFail2banIpsReader is a Reader for the GetFail2banIps structure.
type GetFail2banIpsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFail2banIpsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFail2banIpsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetFail2banIpsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFail2banIpsOK creates a GetFail2banIpsOK with default headers values
func NewGetFail2banIpsOK() *GetFail2banIpsOK {
	return &GetFail2banIpsOK{}
}

/* GetFail2banIpsOK describes a response with status code 200, with default header values.

Successful listing of banned IPs by Fail2ban.
*/
type GetFail2banIpsOK struct {
	Payload *models.Fail2banListItem
}

func (o *GetFail2banIpsOK) Error() string {
	return fmt.Sprintf("[GET /fail2ban][%d] getFail2banIpsOK  %+v", 200, o.Payload)
}
func (o *GetFail2banIpsOK) GetPayload() *models.Fail2banListItem {
	return o.Payload
}

func (o *GetFail2banIpsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Fail2banListItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFail2banIpsInternalServerError creates a GetFail2banIpsInternalServerError with default headers values
func NewGetFail2banIpsInternalServerError() *GetFail2banIpsInternalServerError {
	return &GetFail2banIpsInternalServerError{}
}

/* GetFail2banIpsInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type GetFail2banIpsInternalServerError struct {
}

func (o *GetFail2banIpsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /fail2ban][%d] getFail2banIpsInternalServerError ", 500)
}

func (o *GetFail2banIpsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
