// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFail2banIpsParams creates a new GetFail2banIpsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFail2banIpsParams() *GetFail2banIpsParams {
	return &GetFail2banIpsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFail2banIpsParamsWithTimeout creates a new GetFail2banIpsParams object
// with the ability to set a timeout on a request.
func NewGetFail2banIpsParamsWithTimeout(timeout time.Duration) *GetFail2banIpsParams {
	return &GetFail2banIpsParams{
		timeout: timeout,
	}
}

// NewGetFail2banIpsParamsWithContext creates a new GetFail2banIpsParams object
// with the ability to set a context for a request.
func NewGetFail2banIpsParamsWithContext(ctx context.Context) *GetFail2banIpsParams {
	return &GetFail2banIpsParams{
		Context: ctx,
	}
}

// NewGetFail2banIpsParamsWithHTTPClient creates a new GetFail2banIpsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFail2banIpsParamsWithHTTPClient(client *http.Client) *GetFail2banIpsParams {
	return &GetFail2banIpsParams{
		HTTPClient: client,
	}
}

/* GetFail2banIpsParams contains all the parameters to send to the API endpoint
   for the get fail2ban ips operation.

   Typically these are written to a http.Request.
*/
type GetFail2banIpsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fail2ban ips params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFail2banIpsParams) WithDefaults() *GetFail2banIpsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fail2ban ips params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFail2banIpsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get fail2ban ips params
func (o *GetFail2banIpsParams) WithTimeout(timeout time.Duration) *GetFail2banIpsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fail2ban ips params
func (o *GetFail2banIpsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fail2ban ips params
func (o *GetFail2banIpsParams) WithContext(ctx context.Context) *GetFail2banIpsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fail2ban ips params
func (o *GetFail2banIpsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fail2ban ips params
func (o *GetFail2banIpsParams) WithHTTPClient(client *http.Client) *GetFail2banIpsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fail2ban ips params
func (o *GetFail2banIpsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFail2banIpsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
