// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostFail2banIPReader is a Reader for the PostFail2banIP structure.
type PostFail2banIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFail2banIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostFail2banIPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 405:
		result := NewPostFail2banIPMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostFail2banIPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostFail2banIPOK creates a PostFail2banIPOK with default headers values
func NewPostFail2banIPOK() *PostFail2banIPOK {
	return &PostFail2banIPOK{}
}

/* PostFail2banIPOK describes a response with status code 200, with default header values.

Successful operation
*/
type PostFail2banIPOK struct {
}

func (o *PostFail2banIPOK) Error() string {
	return fmt.Sprintf("[POST /fail2ban][%d] postFail2banIpOK ", 200)
}

func (o *PostFail2banIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostFail2banIPMethodNotAllowed creates a PostFail2banIPMethodNotAllowed with default headers values
func NewPostFail2banIPMethodNotAllowed() *PostFail2banIPMethodNotAllowed {
	return &PostFail2banIPMethodNotAllowed{}
}

/* PostFail2banIPMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type PostFail2banIPMethodNotAllowed struct {
}

func (o *PostFail2banIPMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /fail2ban][%d] postFail2banIpMethodNotAllowed ", 405)
}

func (o *PostFail2banIPMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostFail2banIPInternalServerError creates a PostFail2banIPInternalServerError with default headers values
func NewPostFail2banIPInternalServerError() *PostFail2banIPInternalServerError {
	return &PostFail2banIPInternalServerError{}
}

/* PostFail2banIPInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type PostFail2banIPInternalServerError struct {
}

func (o *PostFail2banIPInternalServerError) Error() string {
	return fmt.Sprintf("[POST /fail2ban][%d] postFail2banIpInternalServerError ", 500)
}

func (o *PostFail2banIPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
