// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddEmailAliasOKCode is the HTTP code returned for type AddEmailAliasOK
const AddEmailAliasOKCode int = 200

/*AddEmailAliasOK Successful operation

swagger:response addEmailAliasOK
*/
type AddEmailAliasOK struct {
}

// NewAddEmailAliasOK creates AddEmailAliasOK with default headers values
func NewAddEmailAliasOK() *AddEmailAliasOK {

	return &AddEmailAliasOK{}
}

// WriteResponse to the client
func (o *AddEmailAliasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddEmailAliasMethodNotAllowedCode is the HTTP code returned for type AddEmailAliasMethodNotAllowed
const AddEmailAliasMethodNotAllowedCode int = 405

/*AddEmailAliasMethodNotAllowed Invalid input

swagger:response addEmailAliasMethodNotAllowed
*/
type AddEmailAliasMethodNotAllowed struct {
}

// NewAddEmailAliasMethodNotAllowed creates AddEmailAliasMethodNotAllowed with default headers values
func NewAddEmailAliasMethodNotAllowed() *AddEmailAliasMethodNotAllowed {

	return &AddEmailAliasMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddEmailAliasMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// AddEmailAliasNotAcceptableCode is the HTTP code returned for type AddEmailAliasNotAcceptable
const AddEmailAliasNotAcceptableCode int = 406

/*AddEmailAliasNotAcceptable Email alias already exists!

swagger:response addEmailAliasNotAcceptable
*/
type AddEmailAliasNotAcceptable struct {
}

// NewAddEmailAliasNotAcceptable creates AddEmailAliasNotAcceptable with default headers values
func NewAddEmailAliasNotAcceptable() *AddEmailAliasNotAcceptable {

	return &AddEmailAliasNotAcceptable{}
}

// WriteResponse to the client
func (o *AddEmailAliasNotAcceptable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(406)
}

// AddEmailAliasInternalServerErrorCode is the HTTP code returned for type AddEmailAliasInternalServerError
const AddEmailAliasInternalServerErrorCode int = 500

/*AddEmailAliasInternalServerError Internal error

swagger:response addEmailAliasInternalServerError
*/
type AddEmailAliasInternalServerError struct {
}

// NewAddEmailAliasInternalServerError creates AddEmailAliasInternalServerError with default headers values
func NewAddEmailAliasInternalServerError() *AddEmailAliasInternalServerError {

	return &AddEmailAliasInternalServerError{}
}

// WriteResponse to the client
func (o *AddEmailAliasInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
