// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddEmailAliasHandlerFunc turns a function with the right signature into a add email alias handler
type AddEmailAliasHandlerFunc func(AddEmailAliasParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddEmailAliasHandlerFunc) Handle(params AddEmailAliasParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddEmailAliasHandler interface for that can handle valid add email alias params
type AddEmailAliasHandler interface {
	Handle(AddEmailAliasParams, interface{}) middleware.Responder
}

// NewAddEmailAlias creates a new http.Handler for the add email alias operation
func NewAddEmailAlias(ctx *middleware.Context, handler AddEmailAliasHandler) *AddEmailAlias {
	return &AddEmailAlias{Context: ctx, Handler: handler}
}

/* AddEmailAlias swagger:route POST /email/{emailAddress}/aliasses email alias addEmailAlias

AddEmailAlias add email alias API

*/
type AddEmailAlias struct {
	Context *middleware.Context
	Handler AddEmailAliasHandler
}

func (o *AddEmailAlias) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddEmailAliasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
