// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewAddEmailAliasParams creates a new AddEmailAliasParams object
//
// There are no default values defined in the spec.
func NewAddEmailAliasParams() AddEmailAliasParams {

	return AddEmailAliasParams{}
}

// AddEmailAliasParams contains all the bound params for the add email alias operation
// typically these are obtained from a http.Request
//
// swagger:parameters addEmailAlias
type AddEmailAliasParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Alias to add to the email account
	  Required: true
	  In: body
	*/
	Alias string
	/*Address of the email account to point the alias to.
	  Required: true
	  In: path
	*/
	EmailAddress string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddEmailAliasParams() beforehand.
func (o *AddEmailAliasParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("alias", "body", ""))
			} else {
				res = append(res, errors.NewParseError("alias", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.Alias = body
		}
	} else {
		res = append(res, errors.Required("alias", "body", ""))
	}

	rEmailAddress, rhkEmailAddress, _ := route.Params.GetOK("emailAddress")
	if err := o.bindEmailAddress(rEmailAddress, rhkEmailAddress, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmailAddress binds and validates parameter EmailAddress from path.
func (o *AddEmailAliasParams) bindEmailAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.EmailAddress = raw

	return nil
}
