// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddEmailAccountHandlerFunc turns a function with the right signature into a add email account handler
type AddEmailAccountHandlerFunc func(AddEmailAccountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AddEmailAccountHandlerFunc) Handle(params AddEmailAccountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AddEmailAccountHandler interface for that can handle valid add email account params
type AddEmailAccountHandler interface {
	Handle(AddEmailAccountParams, interface{}) middleware.Responder
}

// NewAddEmailAccount creates a new http.Handler for the add email account operation
func NewAddEmailAccount(ctx *middleware.Context, handler AddEmailAccountHandler) *AddEmailAccount {
	return &AddEmailAccount{Context: ctx, Handler: handler}
}

/* AddEmailAccount swagger:route POST /email email addEmailAccount

AddEmailAccount add email account API

*/
type AddEmailAccount struct {
	Context *middleware.Context
	Handler AddEmailAccountHandler
}

func (o *AddEmailAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddEmailAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
