// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddEmailAccountOKCode is the HTTP code returned for type AddEmailAccountOK
const AddEmailAccountOKCode int = 200

/*AddEmailAccountOK Successful operation

swagger:response addEmailAccountOK
*/
type AddEmailAccountOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddEmailAccountOK creates AddEmailAccountOK with default headers values
func NewAddEmailAccountOK() *AddEmailAccountOK {

	return &AddEmailAccountOK{}
}

// WithPayload adds the payload to the add email account o k response
func (o *AddEmailAccountOK) WithPayload(payload string) *AddEmailAccountOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add email account o k response
func (o *AddEmailAccountOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddEmailAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// AddEmailAccountMethodNotAllowedCode is the HTTP code returned for type AddEmailAccountMethodNotAllowed
const AddEmailAccountMethodNotAllowedCode int = 405

/*AddEmailAccountMethodNotAllowed Invalid input

swagger:response addEmailAccountMethodNotAllowed
*/
type AddEmailAccountMethodNotAllowed struct {
}

// NewAddEmailAccountMethodNotAllowed creates AddEmailAccountMethodNotAllowed with default headers values
func NewAddEmailAccountMethodNotAllowed() *AddEmailAccountMethodNotAllowed {

	return &AddEmailAccountMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddEmailAccountMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// AddEmailAccountNotAcceptableCode is the HTTP code returned for type AddEmailAccountNotAcceptable
const AddEmailAccountNotAcceptableCode int = 406

/*AddEmailAccountNotAcceptable Email address already exists!

swagger:response addEmailAccountNotAcceptable
*/
type AddEmailAccountNotAcceptable struct {
}

// NewAddEmailAccountNotAcceptable creates AddEmailAccountNotAcceptable with default headers values
func NewAddEmailAccountNotAcceptable() *AddEmailAccountNotAcceptable {

	return &AddEmailAccountNotAcceptable{}
}

// WriteResponse to the client
func (o *AddEmailAccountNotAcceptable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(406)
}

// AddEmailAccountInternalServerErrorCode is the HTTP code returned for type AddEmailAccountInternalServerError
const AddEmailAccountInternalServerErrorCode int = 500

/*AddEmailAccountInternalServerError Internal error

swagger:response addEmailAccountInternalServerError
*/
type AddEmailAccountInternalServerError struct {
}

// NewAddEmailAccountInternalServerError creates AddEmailAccountInternalServerError with default headers values
func NewAddEmailAccountInternalServerError() *AddEmailAccountInternalServerError {

	return &AddEmailAccountInternalServerError{}
}

// WriteResponse to the client
func (o *AddEmailAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
