// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteEmailAliasOKCode is the HTTP code returned for type DeleteEmailAliasOK
const DeleteEmailAliasOKCode int = 200

/*DeleteEmailAliasOK Successful operation

swagger:response deleteEmailAliasOK
*/
type DeleteEmailAliasOK struct {
}

// NewDeleteEmailAliasOK creates DeleteEmailAliasOK with default headers values
func NewDeleteEmailAliasOK() *DeleteEmailAliasOK {

	return &DeleteEmailAliasOK{}
}

// WriteResponse to the client
func (o *DeleteEmailAliasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteEmailAliasNotFoundCode is the HTTP code returned for type DeleteEmailAliasNotFound
const DeleteEmailAliasNotFoundCode int = 404

/*DeleteEmailAliasNotFound Account or alias not found

swagger:response deleteEmailAliasNotFound
*/
type DeleteEmailAliasNotFound struct {
}

// NewDeleteEmailAliasNotFound creates DeleteEmailAliasNotFound with default headers values
func NewDeleteEmailAliasNotFound() *DeleteEmailAliasNotFound {

	return &DeleteEmailAliasNotFound{}
}

// WriteResponse to the client
func (o *DeleteEmailAliasNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteEmailAliasMethodNotAllowedCode is the HTTP code returned for type DeleteEmailAliasMethodNotAllowed
const DeleteEmailAliasMethodNotAllowedCode int = 405

/*DeleteEmailAliasMethodNotAllowed Invalid input

swagger:response deleteEmailAliasMethodNotAllowed
*/
type DeleteEmailAliasMethodNotAllowed struct {
}

// NewDeleteEmailAliasMethodNotAllowed creates DeleteEmailAliasMethodNotAllowed with default headers values
func NewDeleteEmailAliasMethodNotAllowed() *DeleteEmailAliasMethodNotAllowed {

	return &DeleteEmailAliasMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteEmailAliasMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// DeleteEmailAliasInternalServerErrorCode is the HTTP code returned for type DeleteEmailAliasInternalServerError
const DeleteEmailAliasInternalServerErrorCode int = 500

/*DeleteEmailAliasInternalServerError Internal error

swagger:response deleteEmailAliasInternalServerError
*/
type DeleteEmailAliasInternalServerError struct {
}

// NewDeleteEmailAliasInternalServerError creates DeleteEmailAliasInternalServerError with default headers values
func NewDeleteEmailAliasInternalServerError() *DeleteEmailAliasInternalServerError {

	return &DeleteEmailAliasInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteEmailAliasInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
