// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteQuotaOfEmailAccountOKCode is the HTTP code returned for type DeleteQuotaOfEmailAccountOK
const DeleteQuotaOfEmailAccountOKCode int = 200

/*DeleteQuotaOfEmailAccountOK Successful operation

swagger:response deleteQuotaOfEmailAccountOK
*/
type DeleteQuotaOfEmailAccountOK struct {
}

// NewDeleteQuotaOfEmailAccountOK creates DeleteQuotaOfEmailAccountOK with default headers values
func NewDeleteQuotaOfEmailAccountOK() *DeleteQuotaOfEmailAccountOK {

	return &DeleteQuotaOfEmailAccountOK{}
}

// WriteResponse to the client
func (o *DeleteQuotaOfEmailAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteQuotaOfEmailAccountNotFoundCode is the HTTP code returned for type DeleteQuotaOfEmailAccountNotFound
const DeleteQuotaOfEmailAccountNotFoundCode int = 404

/*DeleteQuotaOfEmailAccountNotFound Email account not found

swagger:response deleteQuotaOfEmailAccountNotFound
*/
type DeleteQuotaOfEmailAccountNotFound struct {
}

// NewDeleteQuotaOfEmailAccountNotFound creates DeleteQuotaOfEmailAccountNotFound with default headers values
func NewDeleteQuotaOfEmailAccountNotFound() *DeleteQuotaOfEmailAccountNotFound {

	return &DeleteQuotaOfEmailAccountNotFound{}
}

// WriteResponse to the client
func (o *DeleteQuotaOfEmailAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteQuotaOfEmailAccountMethodNotAllowedCode is the HTTP code returned for type DeleteQuotaOfEmailAccountMethodNotAllowed
const DeleteQuotaOfEmailAccountMethodNotAllowedCode int = 405

/*DeleteQuotaOfEmailAccountMethodNotAllowed Invalid input

swagger:response deleteQuotaOfEmailAccountMethodNotAllowed
*/
type DeleteQuotaOfEmailAccountMethodNotAllowed struct {
}

// NewDeleteQuotaOfEmailAccountMethodNotAllowed creates DeleteQuotaOfEmailAccountMethodNotAllowed with default headers values
func NewDeleteQuotaOfEmailAccountMethodNotAllowed() *DeleteQuotaOfEmailAccountMethodNotAllowed {

	return &DeleteQuotaOfEmailAccountMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteQuotaOfEmailAccountMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// DeleteQuotaOfEmailAccountInternalServerErrorCode is the HTTP code returned for type DeleteQuotaOfEmailAccountInternalServerError
const DeleteQuotaOfEmailAccountInternalServerErrorCode int = 500

/*DeleteQuotaOfEmailAccountInternalServerError Internal error

swagger:response deleteQuotaOfEmailAccountInternalServerError
*/
type DeleteQuotaOfEmailAccountInternalServerError struct {
}

// NewDeleteQuotaOfEmailAccountInternalServerError creates DeleteQuotaOfEmailAccountInternalServerError with default headers values
func NewDeleteQuotaOfEmailAccountInternalServerError() *DeleteQuotaOfEmailAccountInternalServerError {

	return &DeleteQuotaOfEmailAccountInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteQuotaOfEmailAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
