// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteQuotaOfEmailAccountHandlerFunc turns a function with the right signature into a delete quota of email account handler
type DeleteQuotaOfEmailAccountHandlerFunc func(DeleteQuotaOfEmailAccountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteQuotaOfEmailAccountHandlerFunc) Handle(params DeleteQuotaOfEmailAccountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteQuotaOfEmailAccountHandler interface for that can handle valid delete quota of email account params
type DeleteQuotaOfEmailAccountHandler interface {
	Handle(DeleteQuotaOfEmailAccountParams, interface{}) middleware.Responder
}

// NewDeleteQuotaOfEmailAccount creates a new http.Handler for the delete quota of email account operation
func NewDeleteQuotaOfEmailAccount(ctx *middleware.Context, handler DeleteQuotaOfEmailAccountHandler) *DeleteQuotaOfEmailAccount {
	return &DeleteQuotaOfEmailAccount{Context: ctx, Handler: handler}
}

/* DeleteQuotaOfEmailAccount swagger:route DELETE /email/{emailAddress}/quota email deleteQuotaOfEmailAccount

DeleteQuotaOfEmailAccount delete quota of email account API

*/
type DeleteQuotaOfEmailAccount struct {
	Context *middleware.Context
	Handler DeleteQuotaOfEmailAccountHandler
}

func (o *DeleteQuotaOfEmailAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteQuotaOfEmailAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
