// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteEmailAliasHandlerFunc turns a function with the right signature into a delete email alias handler
type DeleteEmailAliasHandlerFunc func(DeleteEmailAliasParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteEmailAliasHandlerFunc) Handle(params DeleteEmailAliasParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteEmailAliasHandler interface for that can handle valid delete email alias params
type DeleteEmailAliasHandler interface {
	Handle(DeleteEmailAliasParams, interface{}) middleware.Responder
}

// NewDeleteEmailAlias creates a new http.Handler for the delete email alias operation
func NewDeleteEmailAlias(ctx *middleware.Context, handler DeleteEmailAliasHandler) *DeleteEmailAlias {
	return &DeleteEmailAlias{Context: ctx, Handler: handler}
}

/* DeleteEmailAlias swagger:route DELETE /email/{emailAddress}/aliasses email alias deleteEmailAlias

DeleteEmailAlias delete email alias API

*/
type DeleteEmailAlias struct {
	Context *middleware.Context
	Handler DeleteEmailAliasHandler
}

func (o *DeleteEmailAlias) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteEmailAliasParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
