// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteEmailAccountHandlerFunc turns a function with the right signature into a delete email account handler
type DeleteEmailAccountHandlerFunc func(DeleteEmailAccountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteEmailAccountHandlerFunc) Handle(params DeleteEmailAccountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteEmailAccountHandler interface for that can handle valid delete email account params
type DeleteEmailAccountHandler interface {
	Handle(DeleteEmailAccountParams, interface{}) middleware.Responder
}

// NewDeleteEmailAccount creates a new http.Handler for the delete email account operation
func NewDeleteEmailAccount(ctx *middleware.Context, handler DeleteEmailAccountHandler) *DeleteEmailAccount {
	return &DeleteEmailAccount{Context: ctx, Handler: handler}
}

/* DeleteEmailAccount swagger:route DELETE /email/{emailAddress} email deleteEmailAccount

DeleteEmailAccount delete email account API

*/
type DeleteEmailAccount struct {
	Context *middleware.Context
	Handler DeleteEmailAccountHandler
}

func (o *DeleteEmailAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteEmailAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
