// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetQuotaOfEmailAccountHandlerFunc turns a function with the right signature into a get quota of email account handler
type GetQuotaOfEmailAccountHandlerFunc func(GetQuotaOfEmailAccountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQuotaOfEmailAccountHandlerFunc) Handle(params GetQuotaOfEmailAccountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetQuotaOfEmailAccountHandler interface for that can handle valid get quota of email account params
type GetQuotaOfEmailAccountHandler interface {
	Handle(GetQuotaOfEmailAccountParams, interface{}) middleware.Responder
}

// NewGetQuotaOfEmailAccount creates a new http.Handler for the get quota of email account operation
func NewGetQuotaOfEmailAccount(ctx *middleware.Context, handler GetQuotaOfEmailAccountHandler) *GetQuotaOfEmailAccount {
	return &GetQuotaOfEmailAccount{Context: ctx, Handler: handler}
}

/* GetQuotaOfEmailAccount swagger:route GET /email/{emailAddress}/quota email getQuotaOfEmailAccount

GetQuotaOfEmailAccount get quota of email account API

*/
type GetQuotaOfEmailAccount struct {
	Context *middleware.Context
	Handler GetQuotaOfEmailAccountHandler
}

func (o *GetQuotaOfEmailAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetQuotaOfEmailAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
