// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListEmailAccountsHandlerFunc turns a function with the right signature into a list email accounts handler
type ListEmailAccountsHandlerFunc func(ListEmailAccountsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListEmailAccountsHandlerFunc) Handle(params ListEmailAccountsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListEmailAccountsHandler interface for that can handle valid list email accounts params
type ListEmailAccountsHandler interface {
	Handle(ListEmailAccountsParams, interface{}) middleware.Responder
}

// NewListEmailAccounts creates a new http.Handler for the list email accounts operation
func NewListEmailAccounts(ctx *middleware.Context, handler ListEmailAccountsHandler) *ListEmailAccounts {
	return &ListEmailAccounts{Context: ctx, Handler: handler}
}

/* ListEmailAccounts swagger:route GET /email email listEmailAccounts

ListEmailAccounts list email accounts API

*/
type ListEmailAccounts struct {
	Context *middleware.Context
	Handler ListEmailAccountsHandler
}

func (o *ListEmailAccounts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListEmailAccountsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
