// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutQuotaOfEmailAccountOKCode is the HTTP code returned for type PutQuotaOfEmailAccountOK
const PutQuotaOfEmailAccountOKCode int = 200

/*PutQuotaOfEmailAccountOK Successful operation

swagger:response putQuotaOfEmailAccountOK
*/
type PutQuotaOfEmailAccountOK struct {
}

// NewPutQuotaOfEmailAccountOK creates PutQuotaOfEmailAccountOK with default headers values
func NewPutQuotaOfEmailAccountOK() *PutQuotaOfEmailAccountOK {

	return &PutQuotaOfEmailAccountOK{}
}

// WriteResponse to the client
func (o *PutQuotaOfEmailAccountOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutQuotaOfEmailAccountNotFoundCode is the HTTP code returned for type PutQuotaOfEmailAccountNotFound
const PutQuotaOfEmailAccountNotFoundCode int = 404

/*PutQuotaOfEmailAccountNotFound Email account not found

swagger:response putQuotaOfEmailAccountNotFound
*/
type PutQuotaOfEmailAccountNotFound struct {
}

// NewPutQuotaOfEmailAccountNotFound creates PutQuotaOfEmailAccountNotFound with default headers values
func NewPutQuotaOfEmailAccountNotFound() *PutQuotaOfEmailAccountNotFound {

	return &PutQuotaOfEmailAccountNotFound{}
}

// WriteResponse to the client
func (o *PutQuotaOfEmailAccountNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PutQuotaOfEmailAccountMethodNotAllowedCode is the HTTP code returned for type PutQuotaOfEmailAccountMethodNotAllowed
const PutQuotaOfEmailAccountMethodNotAllowedCode int = 405

/*PutQuotaOfEmailAccountMethodNotAllowed Invalid input

swagger:response putQuotaOfEmailAccountMethodNotAllowed
*/
type PutQuotaOfEmailAccountMethodNotAllowed struct {
}

// NewPutQuotaOfEmailAccountMethodNotAllowed creates PutQuotaOfEmailAccountMethodNotAllowed with default headers values
func NewPutQuotaOfEmailAccountMethodNotAllowed() *PutQuotaOfEmailAccountMethodNotAllowed {

	return &PutQuotaOfEmailAccountMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PutQuotaOfEmailAccountMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// PutQuotaOfEmailAccountInternalServerErrorCode is the HTTP code returned for type PutQuotaOfEmailAccountInternalServerError
const PutQuotaOfEmailAccountInternalServerErrorCode int = 500

/*PutQuotaOfEmailAccountInternalServerError Internal error

swagger:response putQuotaOfEmailAccountInternalServerError
*/
type PutQuotaOfEmailAccountInternalServerError struct {
}

// NewPutQuotaOfEmailAccountInternalServerError creates PutQuotaOfEmailAccountInternalServerError with default headers values
func NewPutQuotaOfEmailAccountInternalServerError() *PutQuotaOfEmailAccountInternalServerError {

	return &PutQuotaOfEmailAccountInternalServerError{}
}

// WriteResponse to the client
func (o *PutQuotaOfEmailAccountInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
