// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutQuotaOfEmailAccountHandlerFunc turns a function with the right signature into a put quota of email account handler
type PutQuotaOfEmailAccountHandlerFunc func(PutQuotaOfEmailAccountParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutQuotaOfEmailAccountHandlerFunc) Handle(params PutQuotaOfEmailAccountParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutQuotaOfEmailAccountHandler interface for that can handle valid put quota of email account params
type PutQuotaOfEmailAccountHandler interface {
	Handle(PutQuotaOfEmailAccountParams, interface{}) middleware.Responder
}

// NewPutQuotaOfEmailAccount creates a new http.Handler for the put quota of email account operation
func NewPutQuotaOfEmailAccount(ctx *middleware.Context, handler PutQuotaOfEmailAccountHandler) *PutQuotaOfEmailAccount {
	return &PutQuotaOfEmailAccount{Context: ctx, Handler: handler}
}

/* PutQuotaOfEmailAccount swagger:route PUT /email/{emailAddress}/quota email putQuotaOfEmailAccount

PutQuotaOfEmailAccount put quota of email account API

*/
type PutQuotaOfEmailAccount struct {
	Context *middleware.Context
	Handler PutQuotaOfEmailAccountHandler
}

func (o *PutQuotaOfEmailAccount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutQuotaOfEmailAccountParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
