// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateEmailAddressOKCode is the HTTP code returned for type UpdateEmailAddressOK
const UpdateEmailAddressOKCode int = 200

/*UpdateEmailAddressOK Successful operation

swagger:response updateEmailAddressOK
*/
type UpdateEmailAddressOK struct {
}

// NewUpdateEmailAddressOK creates UpdateEmailAddressOK with default headers values
func NewUpdateEmailAddressOK() *UpdateEmailAddressOK {

	return &UpdateEmailAddressOK{}
}

// WriteResponse to the client
func (o *UpdateEmailAddressOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateEmailAddressNotFoundCode is the HTTP code returned for type UpdateEmailAddressNotFound
const UpdateEmailAddressNotFoundCode int = 404

/*UpdateEmailAddressNotFound Account not found

swagger:response updateEmailAddressNotFound
*/
type UpdateEmailAddressNotFound struct {
}

// NewUpdateEmailAddressNotFound creates UpdateEmailAddressNotFound with default headers values
func NewUpdateEmailAddressNotFound() *UpdateEmailAddressNotFound {

	return &UpdateEmailAddressNotFound{}
}

// WriteResponse to the client
func (o *UpdateEmailAddressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateEmailAddressMethodNotAllowedCode is the HTTP code returned for type UpdateEmailAddressMethodNotAllowed
const UpdateEmailAddressMethodNotAllowedCode int = 405

/*UpdateEmailAddressMethodNotAllowed Invalid input

swagger:response updateEmailAddressMethodNotAllowed
*/
type UpdateEmailAddressMethodNotAllowed struct {
}

// NewUpdateEmailAddressMethodNotAllowed creates UpdateEmailAddressMethodNotAllowed with default headers values
func NewUpdateEmailAddressMethodNotAllowed() *UpdateEmailAddressMethodNotAllowed {

	return &UpdateEmailAddressMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateEmailAddressMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// UpdateEmailAddressInternalServerErrorCode is the HTTP code returned for type UpdateEmailAddressInternalServerError
const UpdateEmailAddressInternalServerErrorCode int = 500

/*UpdateEmailAddressInternalServerError Internal error

swagger:response updateEmailAddressInternalServerError
*/
type UpdateEmailAddressInternalServerError struct {
}

// NewUpdateEmailAddressInternalServerError creates UpdateEmailAddressInternalServerError with default headers values
func NewUpdateEmailAddressInternalServerError() *UpdateEmailAddressInternalServerError {

	return &UpdateEmailAddressInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateEmailAddressInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
