// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pjotrscholtze/dmailserver-rest-api/models"
)

// NewAddEmailAccountParams creates a new AddEmailAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddEmailAccountParams() *AddEmailAccountParams {
	return &AddEmailAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddEmailAccountParamsWithTimeout creates a new AddEmailAccountParams object
// with the ability to set a timeout on a request.
func NewAddEmailAccountParamsWithTimeout(timeout time.Duration) *AddEmailAccountParams {
	return &AddEmailAccountParams{
		timeout: timeout,
	}
}

// NewAddEmailAccountParamsWithContext creates a new AddEmailAccountParams object
// with the ability to set a context for a request.
func NewAddEmailAccountParamsWithContext(ctx context.Context) *AddEmailAccountParams {
	return &AddEmailAccountParams{
		Context: ctx,
	}
}

// NewAddEmailAccountParamsWithHTTPClient creates a new AddEmailAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddEmailAccountParamsWithHTTPClient(client *http.Client) *AddEmailAccountParams {
	return &AddEmailAccountParams{
		HTTPClient: client,
	}
}

/* AddEmailAccountParams contains all the parameters to send to the API endpoint
   for the add email account operation.

   Typically these are written to a http.Request.
*/
type AddEmailAccountParams struct {

	/* Body.

	   Create a new email account
	*/
	Body *models.EmailAccount

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add email account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddEmailAccountParams) WithDefaults() *AddEmailAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add email account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddEmailAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add email account params
func (o *AddEmailAccountParams) WithTimeout(timeout time.Duration) *AddEmailAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add email account params
func (o *AddEmailAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add email account params
func (o *AddEmailAccountParams) WithContext(ctx context.Context) *AddEmailAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add email account params
func (o *AddEmailAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add email account params
func (o *AddEmailAccountParams) WithHTTPClient(client *http.Client) *AddEmailAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add email account params
func (o *AddEmailAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add email account params
func (o *AddEmailAccountParams) WithBody(body *models.EmailAccount) *AddEmailAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add email account params
func (o *AddEmailAccountParams) SetBody(body *models.EmailAccount) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddEmailAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
