// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEmailAliasParams creates a new DeleteEmailAliasParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEmailAliasParams() *DeleteEmailAliasParams {
	return &DeleteEmailAliasParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEmailAliasParamsWithTimeout creates a new DeleteEmailAliasParams object
// with the ability to set a timeout on a request.
func NewDeleteEmailAliasParamsWithTimeout(timeout time.Duration) *DeleteEmailAliasParams {
	return &DeleteEmailAliasParams{
		timeout: timeout,
	}
}

// NewDeleteEmailAliasParamsWithContext creates a new DeleteEmailAliasParams object
// with the ability to set a context for a request.
func NewDeleteEmailAliasParamsWithContext(ctx context.Context) *DeleteEmailAliasParams {
	return &DeleteEmailAliasParams{
		Context: ctx,
	}
}

// NewDeleteEmailAliasParamsWithHTTPClient creates a new DeleteEmailAliasParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEmailAliasParamsWithHTTPClient(client *http.Client) *DeleteEmailAliasParams {
	return &DeleteEmailAliasParams{
		HTTPClient: client,
	}
}

/* DeleteEmailAliasParams contains all the parameters to send to the API endpoint
   for the delete email alias operation.

   Typically these are written to a http.Request.
*/
type DeleteEmailAliasParams struct {

	/* Alias.

	   Alias to remove from the email account
	*/
	Alias string

	/* EmailAddress.

	   Address of the email account to delete the alias from
	*/
	EmailAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete email alias params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEmailAliasParams) WithDefaults() *DeleteEmailAliasParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete email alias params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEmailAliasParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete email alias params
func (o *DeleteEmailAliasParams) WithTimeout(timeout time.Duration) *DeleteEmailAliasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete email alias params
func (o *DeleteEmailAliasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete email alias params
func (o *DeleteEmailAliasParams) WithContext(ctx context.Context) *DeleteEmailAliasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete email alias params
func (o *DeleteEmailAliasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete email alias params
func (o *DeleteEmailAliasParams) WithHTTPClient(client *http.Client) *DeleteEmailAliasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete email alias params
func (o *DeleteEmailAliasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlias adds the alias to the delete email alias params
func (o *DeleteEmailAliasParams) WithAlias(alias string) *DeleteEmailAliasParams {
	o.SetAlias(alias)
	return o
}

// SetAlias adds the alias to the delete email alias params
func (o *DeleteEmailAliasParams) SetAlias(alias string) {
	o.Alias = alias
}

// WithEmailAddress adds the emailAddress to the delete email alias params
func (o *DeleteEmailAliasParams) WithEmailAddress(emailAddress string) *DeleteEmailAliasParams {
	o.SetEmailAddress(emailAddress)
	return o
}

// SetEmailAddress adds the emailAddress to the delete email alias params
func (o *DeleteEmailAliasParams) SetEmailAddress(emailAddress string) {
	o.EmailAddress = emailAddress
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEmailAliasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Alias); err != nil {
		return err
	}

	// path param emailAddress
	if err := r.SetPathParam("emailAddress", o.EmailAddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
