// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEmailAccountParams creates a new DeleteEmailAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEmailAccountParams() *DeleteEmailAccountParams {
	return &DeleteEmailAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEmailAccountParamsWithTimeout creates a new DeleteEmailAccountParams object
// with the ability to set a timeout on a request.
func NewDeleteEmailAccountParamsWithTimeout(timeout time.Duration) *DeleteEmailAccountParams {
	return &DeleteEmailAccountParams{
		timeout: timeout,
	}
}

// NewDeleteEmailAccountParamsWithContext creates a new DeleteEmailAccountParams object
// with the ability to set a context for a request.
func NewDeleteEmailAccountParamsWithContext(ctx context.Context) *DeleteEmailAccountParams {
	return &DeleteEmailAccountParams{
		Context: ctx,
	}
}

// NewDeleteEmailAccountParamsWithHTTPClient creates a new DeleteEmailAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEmailAccountParamsWithHTTPClient(client *http.Client) *DeleteEmailAccountParams {
	return &DeleteEmailAccountParams{
		HTTPClient: client,
	}
}

/* DeleteEmailAccountParams contains all the parameters to send to the API endpoint
   for the delete email account operation.

   Typically these are written to a http.Request.
*/
type DeleteEmailAccountParams struct {

	/* EmailAddress.

	   Address of the email account to delete
	*/
	EmailAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete email account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEmailAccountParams) WithDefaults() *DeleteEmailAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete email account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEmailAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete email account params
func (o *DeleteEmailAccountParams) WithTimeout(timeout time.Duration) *DeleteEmailAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete email account params
func (o *DeleteEmailAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete email account params
func (o *DeleteEmailAccountParams) WithContext(ctx context.Context) *DeleteEmailAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete email account params
func (o *DeleteEmailAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete email account params
func (o *DeleteEmailAccountParams) WithHTTPClient(client *http.Client) *DeleteEmailAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete email account params
func (o *DeleteEmailAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmailAddress adds the emailAddress to the delete email account params
func (o *DeleteEmailAccountParams) WithEmailAddress(emailAddress string) *DeleteEmailAccountParams {
	o.SetEmailAddress(emailAddress)
	return o
}

// SetEmailAddress adds the emailAddress to the delete email account params
func (o *DeleteEmailAccountParams) SetEmailAddress(emailAddress string) {
	o.EmailAddress = emailAddress
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEmailAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param emailAddress
	if err := r.SetPathParam("emailAddress", o.EmailAddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
