// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListEmailAccountsParams creates a new ListEmailAccountsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListEmailAccountsParams() *ListEmailAccountsParams {
	return &ListEmailAccountsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListEmailAccountsParamsWithTimeout creates a new ListEmailAccountsParams object
// with the ability to set a timeout on a request.
func NewListEmailAccountsParamsWithTimeout(timeout time.Duration) *ListEmailAccountsParams {
	return &ListEmailAccountsParams{
		timeout: timeout,
	}
}

// NewListEmailAccountsParamsWithContext creates a new ListEmailAccountsParams object
// with the ability to set a context for a request.
func NewListEmailAccountsParamsWithContext(ctx context.Context) *ListEmailAccountsParams {
	return &ListEmailAccountsParams{
		Context: ctx,
	}
}

// NewListEmailAccountsParamsWithHTTPClient creates a new ListEmailAccountsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListEmailAccountsParamsWithHTTPClient(client *http.Client) *ListEmailAccountsParams {
	return &ListEmailAccountsParams{
		HTTPClient: client,
	}
}

/* ListEmailAccountsParams contains all the parameters to send to the API endpoint
   for the list email accounts operation.

   Typically these are written to a http.Request.
*/
type ListEmailAccountsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list email accounts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEmailAccountsParams) WithDefaults() *ListEmailAccountsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list email accounts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEmailAccountsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list email accounts params
func (o *ListEmailAccountsParams) WithTimeout(timeout time.Duration) *ListEmailAccountsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list email accounts params
func (o *ListEmailAccountsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list email accounts params
func (o *ListEmailAccountsParams) WithContext(ctx context.Context) *ListEmailAccountsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list email accounts params
func (o *ListEmailAccountsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list email accounts params
func (o *ListEmailAccountsParams) WithHTTPClient(client *http.Client) *ListEmailAccountsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list email accounts params
func (o *ListEmailAccountsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListEmailAccountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
