// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pjotrscholtze/dmailserver-rest-api/models"
)

// ListEmailAccountsReader is a Reader for the ListEmailAccounts structure.
type ListEmailAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEmailAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListEmailAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListEmailAccountsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListEmailAccountsOK creates a ListEmailAccountsOK with default headers values
func NewListEmailAccountsOK() *ListEmailAccountsOK {
	return &ListEmailAccountsOK{}
}

/* ListEmailAccountsOK describes a response with status code 200, with default header values.

Successful listing of email addresses
*/
type ListEmailAccountsOK struct {
	Payload []*models.EmailAccountListItem
}

func (o *ListEmailAccountsOK) Error() string {
	return fmt.Sprintf("[GET /email][%d] listEmailAccountsOK  %+v", 200, o.Payload)
}
func (o *ListEmailAccountsOK) GetPayload() []*models.EmailAccountListItem {
	return o.Payload
}

func (o *ListEmailAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEmailAccountsInternalServerError creates a ListEmailAccountsInternalServerError with default headers values
func NewListEmailAccountsInternalServerError() *ListEmailAccountsInternalServerError {
	return &ListEmailAccountsInternalServerError{}
}

/* ListEmailAccountsInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type ListEmailAccountsInternalServerError struct {
}

func (o *ListEmailAccountsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /email][%d] listEmailAccountsInternalServerError ", 500)
}

func (o *ListEmailAccountsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
