// Code generated by go-swagger; DO NOT EDIT.

package email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateEmailAddressParams creates a new UpdateEmailAddressParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateEmailAddressParams() *UpdateEmailAddressParams {
	return &UpdateEmailAddressParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEmailAddressParamsWithTimeout creates a new UpdateEmailAddressParams object
// with the ability to set a timeout on a request.
func NewUpdateEmailAddressParamsWithTimeout(timeout time.Duration) *UpdateEmailAddressParams {
	return &UpdateEmailAddressParams{
		timeout: timeout,
	}
}

// NewUpdateEmailAddressParamsWithContext creates a new UpdateEmailAddressParams object
// with the ability to set a context for a request.
func NewUpdateEmailAddressParamsWithContext(ctx context.Context) *UpdateEmailAddressParams {
	return &UpdateEmailAddressParams{
		Context: ctx,
	}
}

// NewUpdateEmailAddressParamsWithHTTPClient creates a new UpdateEmailAddressParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateEmailAddressParamsWithHTTPClient(client *http.Client) *UpdateEmailAddressParams {
	return &UpdateEmailAddressParams{
		HTTPClient: client,
	}
}

/* UpdateEmailAddressParams contains all the parameters to send to the API endpoint
   for the update email address operation.

   Typically these are written to a http.Request.
*/
type UpdateEmailAddressParams struct {

	/* EmailAddress.

	   Address of the email account to update
	*/
	EmailAddress string

	/* Password.

	   Password for the email account
	*/
	Password string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update email address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEmailAddressParams) WithDefaults() *UpdateEmailAddressParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update email address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEmailAddressParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update email address params
func (o *UpdateEmailAddressParams) WithTimeout(timeout time.Duration) *UpdateEmailAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update email address params
func (o *UpdateEmailAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update email address params
func (o *UpdateEmailAddressParams) WithContext(ctx context.Context) *UpdateEmailAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update email address params
func (o *UpdateEmailAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update email address params
func (o *UpdateEmailAddressParams) WithHTTPClient(client *http.Client) *UpdateEmailAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update email address params
func (o *UpdateEmailAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmailAddress adds the emailAddress to the update email address params
func (o *UpdateEmailAddressParams) WithEmailAddress(emailAddress string) *UpdateEmailAddressParams {
	o.SetEmailAddress(emailAddress)
	return o
}

// SetEmailAddress adds the emailAddress to the update email address params
func (o *UpdateEmailAddressParams) SetEmailAddress(emailAddress string) {
	o.EmailAddress = emailAddress
}

// WithPassword adds the password to the update email address params
func (o *UpdateEmailAddressParams) WithPassword(password string) *UpdateEmailAddressParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the update email address params
func (o *UpdateEmailAddressParams) SetPassword(password string) {
	o.Password = password
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEmailAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param emailAddress
	if err := r.SetPathParam("emailAddress", o.EmailAddress); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Password); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
