// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFail2banIPOKCode is the HTTP code returned for type DeleteFail2banIPOK
const DeleteFail2banIPOKCode int = 200

/*DeleteFail2banIPOK Successful operation

swagger:response deleteFail2banIpOK
*/
type DeleteFail2banIPOK struct {
}

// NewDeleteFail2banIPOK creates DeleteFail2banIPOK with default headers values
func NewDeleteFail2banIPOK() *DeleteFail2banIPOK {

	return &DeleteFail2banIPOK{}
}

// WriteResponse to the client
func (o *DeleteFail2banIPOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteFail2banIPNotFoundCode is the HTTP code returned for type DeleteFail2banIPNotFound
const DeleteFail2banIPNotFoundCode int = 404

/*DeleteFail2banIPNotFound IP was not found

swagger:response deleteFail2banIpNotFound
*/
type DeleteFail2banIPNotFound struct {
}

// NewDeleteFail2banIPNotFound creates DeleteFail2banIPNotFound with default headers values
func NewDeleteFail2banIPNotFound() *DeleteFail2banIPNotFound {

	return &DeleteFail2banIPNotFound{}
}

// WriteResponse to the client
func (o *DeleteFail2banIPNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteFail2banIPMethodNotAllowedCode is the HTTP code returned for type DeleteFail2banIPMethodNotAllowed
const DeleteFail2banIPMethodNotAllowedCode int = 405

/*DeleteFail2banIPMethodNotAllowed Invalid input

swagger:response deleteFail2banIpMethodNotAllowed
*/
type DeleteFail2banIPMethodNotAllowed struct {
}

// NewDeleteFail2banIPMethodNotAllowed creates DeleteFail2banIPMethodNotAllowed with default headers values
func NewDeleteFail2banIPMethodNotAllowed() *DeleteFail2banIPMethodNotAllowed {

	return &DeleteFail2banIPMethodNotAllowed{}
}

// WriteResponse to the client
func (o *DeleteFail2banIPMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// DeleteFail2banIPInternalServerErrorCode is the HTTP code returned for type DeleteFail2banIPInternalServerError
const DeleteFail2banIPInternalServerErrorCode int = 500

/*DeleteFail2banIPInternalServerError Internal error

swagger:response deleteFail2banIpInternalServerError
*/
type DeleteFail2banIPInternalServerError struct {
}

// NewDeleteFail2banIPInternalServerError creates DeleteFail2banIPInternalServerError with default headers values
func NewDeleteFail2banIPInternalServerError() *DeleteFail2banIPInternalServerError {

	return &DeleteFail2banIPInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteFail2banIPInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
