// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteFail2banIPParams creates a new DeleteFail2banIPParams object
//
// There are no default values defined in the spec.
func NewDeleteFail2banIPParams() DeleteFail2banIPParams {

	return DeleteFail2banIPParams{}
}

// DeleteFail2banIPParams contains all the bound params for the delete fail2ban Ip operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteFail2banIp
type DeleteFail2banIPParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*IP address to delete
	  Required: true
	  In: path
	*/
	IP string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteFail2banIPParams() beforehand.
func (o *DeleteFail2banIPParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIP, rhkIP, _ := route.Params.GetOK("ip")
	if err := o.bindIP(rIP, rhkIP, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIP binds and validates parameter IP from path.
func (o *DeleteFail2banIPParams) bindIP(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.IP = raw

	return nil
}
