// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetFail2banIpsParams creates a new GetFail2banIpsParams object
//
// There are no default values defined in the spec.
func NewGetFail2banIpsParams() GetFail2banIpsParams {

	return GetFail2banIpsParams{}
}

// GetFail2banIpsParams contains all the bound params for the get fail2ban ips operation
// typically these are obtained from a http.Request
//
// swagger:parameters getFail2banIps
type GetFail2banIpsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFail2banIpsParams() beforehand.
func (o *GetFail2banIpsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
