// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFail2banIpsHandlerFunc turns a function with the right signature into a get fail2ban ips handler
type GetFail2banIpsHandlerFunc func(GetFail2banIpsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFail2banIpsHandlerFunc) Handle(params GetFail2banIpsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetFail2banIpsHandler interface for that can handle valid get fail2ban ips params
type GetFail2banIpsHandler interface {
	Handle(GetFail2banIpsParams, interface{}) middleware.Responder
}

// NewGetFail2banIps creates a new http.Handler for the get fail2ban ips operation
func NewGetFail2banIps(ctx *middleware.Context, handler GetFail2banIpsHandler) *GetFail2banIps {
	return &GetFail2banIps{Context: ctx, Handler: handler}
}

/* GetFail2banIps swagger:route GET /fail2ban fail2ban getFail2banIps

GetFail2banIps get fail2ban ips API

*/
type GetFail2banIps struct {
	Context *middleware.Context
	Handler GetFail2banIpsHandler
}

func (o *GetFail2banIps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFail2banIpsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
