// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pjotrscholtze/dmailserver-rest-api/models"
)

// GetFail2banIpsOKCode is the HTTP code returned for type GetFail2banIpsOK
const GetFail2banIpsOKCode int = 200

/*GetFail2banIpsOK Successful listing of banned IPs by Fail2ban.

swagger:response getFail2banIpsOK
*/
type GetFail2banIpsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Fail2banListItem `json:"body,omitempty"`
}

// NewGetFail2banIpsOK creates GetFail2banIpsOK with default headers values
func NewGetFail2banIpsOK() *GetFail2banIpsOK {

	return &GetFail2banIpsOK{}
}

// WithPayload adds the payload to the get fail2ban ips o k response
func (o *GetFail2banIpsOK) WithPayload(payload *models.Fail2banListItem) *GetFail2banIpsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get fail2ban ips o k response
func (o *GetFail2banIpsOK) SetPayload(payload *models.Fail2banListItem) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFail2banIpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFail2banIpsInternalServerErrorCode is the HTTP code returned for type GetFail2banIpsInternalServerError
const GetFail2banIpsInternalServerErrorCode int = 500

/*GetFail2banIpsInternalServerError Internal error

swagger:response getFail2banIpsInternalServerError
*/
type GetFail2banIpsInternalServerError struct {
}

// NewGetFail2banIpsInternalServerError creates GetFail2banIpsInternalServerError with default headers values
func NewGetFail2banIpsInternalServerError() *GetFail2banIpsInternalServerError {

	return &GetFail2banIpsInternalServerError{}
}

// WriteResponse to the client
func (o *GetFail2banIpsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
