// Code generated by go-swagger; DO NOT EDIT.

package fail2ban

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostFail2banIPHandlerFunc turns a function with the right signature into a post fail2ban Ip handler
type PostFail2banIPHandlerFunc func(PostFail2banIPParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFail2banIPHandlerFunc) Handle(params PostFail2banIPParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostFail2banIPHandler interface for that can handle valid post fail2ban Ip params
type PostFail2banIPHandler interface {
	Handle(PostFail2banIPParams, interface{}) middleware.Responder
}

// NewPostFail2banIP creates a new http.Handler for the post fail2ban Ip operation
func NewPostFail2banIP(ctx *middleware.Context, handler PostFail2banIPHandler) *PostFail2banIP {
	return &PostFail2banIP{Context: ctx, Handler: handler}
}

/* PostFail2banIP swagger:route POST /fail2ban fail2ban postFail2banIp

PostFail2banIP post fail2ban Ip API

*/
type PostFail2banIP struct {
	Context *middleware.Context
	Handler PostFail2banIPHandler
}

func (o *PostFail2banIP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostFail2banIPParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
