// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Fail2banListItem fail2ban list item
//
// swagger:model Fail2banListItem
type Fail2banListItem struct {

	// banned in dovecot
	BannedInDovecot []string `json:"bannedInDovecot"`

	// banned in postfix
	BannedInPostfix []string `json:"bannedInPostfix"`

	// banned in postfix sasl
	BannedInPostfixSasl []string `json:"bannedInPostfixSasl"`
}

// Validate validates this fail2ban list item
func (m *Fail2banListItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this fail2ban list item based on context it is used
func (m *Fail2banListItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Fail2banListItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Fail2banListItem) UnmarshalBinary(b []byte) error {
	var res Fail2banListItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
